// ═══════════════════════════════════════════════════════════════════════════════
// SEED — CZARY OFENSYWNE
// src/prisma/seed-spells-offensive.ts
//
// Czary bojowe ofensywne: zadają obrażenia i/lub nakładają statusy ofensywne.
// Dostępne statusy: dot, vulnerable, damage_on_move, stun
// ═══════════════════════════════════════════════════════════════════════════════

import type { StatusEffectDef } from "../src/types/status-types.js";

function fx(effects: StatusEffectDef[]): string {
  return JSON.stringify(effects);
}

export const OFFENSIVE_SPELLS = [

  // ════════════════════════════════════════════════════════════════════════════
  // CZARY BEZPOŚREDNIE — czyste obrażenia, brak statusów
  // ════════════════════════════════════════════════════════════════════════════

  // ── Pula chaotyczna — podstawowe czary ───────────────────────────────────

  {
    name: "Pomniejsze przywołanie",
    category: "offensive", spellPool: "chaotic",
    rarity: "common", element: "none",
    bookDescription: "Przypadkowy przedmiot materializuje się nad głową przeciwnika i spada.",
    damage: 1, basicCost: 0,
    spellTarget: "randomEnemy",
    isTutorialReward: true,
    special: "Nad {target} materializuje się przypadkowy przedmiot i z hukiem spada zadając {damage} obrażeń.",
    statusEffects: fx([]),
  },

  {
    name: "Cegła",
    category: "offensive", spellPool: "chaotic",
    rarity: "common", element: "none",
    bookDescription: "Cegła spada na głowę nieprzyjaciela.",
    damage: 2, basicCost: 0,
    spellTarget: "randomEnemy",
    special: "Nad {target} materializuje się cegła, która spadając zadaje {damage} obrażeń.",
    statusEffects: fx([]),
  },

  {
    name: "Kłoda",
    category: "offensive", spellPool: "chaotic",
    rarity: "common", element: "none",
    bookDescription: "Potężna kłoda spada na wybranego przeciwnika.",
    damage: 5, basicCost: 0,
    spellTarget: "randomEnemy",
    special: "Nad {target} materializuje się pokaźna kłoda, która spadając zadaje {damage} obrażeń.",
    statusEffects: fx([]),
  },

  // ── Pociski żywiołów — seria trójpoziomowa ───────────────────────────────

  {
    name: "Pomniejszy pocisk chaosu",
    category: "offensive", spellPool: "chaotic",
    rarity: "common", element: "chaos",
    bookDescription: "Podstawowy pocisk z energii chaosu.",
    damage: 7, basicCost: 0,
    reqBloodMagic: 15,
    spellTarget: "randomEnemy",
    special: "Fioletowy pocisk chaosu uderza w {target} zadając {damage} obrażeń.",
    statusEffects: fx([]),
  },
  {
    name: "Pocisk chaosu",
    category: "offensive", spellPool: "controlled",
    rarity: "common", element: "chaos",
    bookDescription: "Wzmocniony pocisk energii chaosu.",
    damage: 14, basicCost: 0,
    reqBloodMagic: 30,
    spellTarget: "randomEnemy",
    special: "Potężny fioletowy pocisk chaosu uderza w {target} zadając {damage} obrażeń.",
    statusEffects: fx([]),
  },
  {
    name: "Potężny pocisk chaosu",
    category: "offensive", spellPool: "incantation",
    rarity: "common", element: "chaos",
    bookDescription: "Zaawansowany pocisk energii chaosu.",
    damage: 25, basicCost: 0,
    reqBloodMagic: 45,
    spellTarget: "randomEnemy",
    special: "Ogromny fioletowy pocisk chaosu niszczy {target} zadając {damage} obrażeń.",
    statusEffects: fx([]),
  },

  {
    name: "Pomniejsza wiązka energii",
    category: "offensive", spellPool: "chaotic",
    rarity: "common", element: "energy",
    bookDescription: "Słaba wiązka astralnej energii.",
    damage: 5, basicCost: 0,
    reqAstralMagic: 5,
    spellTarget: "randomEnemy",
    special: "Wiązka energii razi {target} zadając {damage} obrażeń.",
    statusEffects: fx([]),
  },
  {
    name: "Wiązka energii",
    category: "offensive", spellPool: "controlled",
    rarity: "common", element: "energy",
    bookDescription: "Solidna wiązka astralnej energii.",
    damage: 10, basicCost: 0,
    reqAstralMagic: 20,
    spellTarget: "randomEnemy",
    special: "Potężna wiązka energii razi {target} zadając {damage} obrażeń.",
    statusEffects: fx([]),
  },
  {
    name: "Potężna wiązka energii",
    category: "offensive", spellPool: "incantation",
    rarity: "common", element: "energy",
    bookDescription: "Niszcząca wiązka astralnej energii.",
    damage: 15, basicCost: 0,
    reqAstralMagic: 35,
    spellTarget: "randomEnemy",
    special: "Niszcząca wiązka energii razi {target} zadając {damage} obrażeń.",
    statusEffects: fx([]),
  },

  {
    name: "Pomniejszy pocisk lodowy",
    category: "offensive", spellPool: "chaotic",
    rarity: "common", element: "water",
    bookDescription: "Lodowe sople uderzają w cel.",
    damage: 5, basicCost: 0,
    reqElementalMagic: 5,
    spellTarget: "randomEnemy",
    special: "Lodowe sople uderzają w {target} zadając {damage} obrażeń.",
    statusEffects: fx([]),
  },
  {
    name: "Pocisk lodowy",
    category: "offensive", spellPool: "controlled",
    rarity: "common", element: "water",
    bookDescription: "Większe lodowe sople atakują cel.",
    damage: 10, basicCost: 0,
    reqElementalMagic: 20,
    spellTarget: "randomEnemy",
    special: "Duże lodowe sople uderzają w {target} zadając {damage} obrażeń.",
    statusEffects: fx([]),
  },
  {
    name: "Potężny pocisk lodowy",
    category: "offensive", spellPool: "incantation",
    rarity: "common", element: "water",
    bookDescription: "Potężny lodowy pocisk druzgoce cel.",
    damage: 15, basicCost: 0,
    reqElementalMagic: 35,
    spellTarget: "randomEnemy",
    special: "Potężny lodowy pocisk druzgoce {target} zadając {damage} obrażeń.",
    statusEffects: fx([]),
  },

  {
    name: "Pomniejsza ognista strzała",
    category: "offensive", spellPool: "chaotic",
    rarity: "common", element: "fire",
    bookDescription: "Płonąca strzała atakuje wybranego wroga.",
    damage: 5, basicCost: 0,
    reqElementalMagic: 5,
    spellTarget: "randomEnemy",
    special: "Ognista strzała uderza w {target} zadając {damage} obrażeń.",
    statusEffects: fx([]),
  },
  {
    name: "Ognista strzała",
    category: "offensive", spellPool: "controlled",
    rarity: "common", element: "fire",
    bookDescription: "Silniejsza płonąca strzała.",
    damage: 10, basicCost: 0,
    reqElementalMagic: 20,
    spellTarget: "randomEnemy",
    special: "Potężna ognista strzała uderza w {target} zadając {damage} obrażeń.",
    statusEffects: fx([]),
  },
  {
    name: "Potężna ognista strzała",
    category: "offensive", spellPool: "incantation",
    rarity: "common", element: "fire",
    bookDescription: "Niszcząca płonąca strzała.",
    damage: 15, basicCost: 0,
    reqElementalMagic: 35,
    spellTarget: "randomEnemy",
    special: "Niszcząca ognista strzała uderza w {target} zadając {damage} obrażeń.",
    statusEffects: fx([]),
  },

  {
    name: "Pomniejsza pięść wiatru",
    category: "offensive", spellPool: "chaotic",
    rarity: "common", element: "air",
    bookDescription: "Uderzenie wiatru trafia w cel.",
    damage: 5, basicCost: 0,
    reqElementalMagic: 5,
    spellTarget: "randomEnemy",
    special: "Uderzenie wiatru trafia w {target} zadając {damage} obrażeń.",
    statusEffects: fx([]),
  },
  {
    name: "Pięść wiatru",
    category: "offensive", spellPool: "controlled",
    rarity: "common", element: "air",
    bookDescription: "Silniejsze uderzenie wiatru.",
    damage: 10, basicCost: 0,
    reqElementalMagic: 20,
    spellTarget: "randomEnemy",
    special: "Potężne uderzenie wiatru trafia w {target} zadając {damage} obrażeń.",
    statusEffects: fx([]),
  },
  {
    name: "Potężna pięść wiatru",
    category: "offensive", spellPool: "incantation",
    rarity: "common", element: "air",
    bookDescription: "Niszczące uderzenie wiatru.",
    damage: 15, basicCost: 0,
    reqElementalMagic: 35,
    spellTarget: "randomEnemy",
    special: "Niszczące uderzenie wiatru trafia w {target} zadając {damage} obrażeń.",
    statusEffects: fx([]),
  },

  {
    name: "Kamień",
    category: "offensive", spellPool: "chaotic",
    rarity: "common", element: "earth",
    bookDescription: "Kamień spada na wroga.",
    damage: 5, basicCost: 0,
    reqElementalMagic: 5,
    spellTarget: "randomEnemy",
    special: "Nad {target} materializuje się kamień, który spadając zadaje {damage} obrażeń.",
    statusEffects: fx([]),
  },
  {
    name: "Duży kamień",
    category: "offensive", spellPool: "controlled",
    rarity: "common", element: "earth",
    bookDescription: "Większy kamień spada na wroga.",
    damage: 10, basicCost: 0,
    reqElementalMagic: 20,
    spellTarget: "randomEnemy",
    special: "Nad {target} materializuje się duży kamień, który spadając zadaje {damage} obrażeń.",
    statusEffects: fx([]),
  },
  {
    name: "Głaz",
    category: "offensive", spellPool: "incantation",
    rarity: "common", element: "earth",
    bookDescription: "Potężny głaz spada na wroga.",
    damage: 15, basicCost: 0,
    reqElementalMagic: 35,
    spellTarget: "randomEnemy",
    special: "Nad {target} materializuje się potężny głaz, który zadaje {damage} obrażeń.",
    statusEffects: fx([]),
  },

  // ════════════════════════════════════════════════════════════════════════════
  // DOT — obrażenia co turę
  // ════════════════════════════════════════════════════════════════════════════

  {
    name: "Zatrucie",
    category: "offensive", spellPool: "chaotic",
    rarity: "uncommon", element: "death",
    bookDescription: "Zatruwa wybranego przeciwnika, który co turę otrzymuje obrażenia.",
    damage: 0, basicCost: 0,
    reqBloodMagic: 5,
    spellTarget: "randomEnemy",
    special: "Trujące substancje wnikają w ciało {target}!",
    endInfo: "Zatrucie {target} mija.",
    statusEffects: fx([{
      type: "dot",
      element: "death",
      damage: 3,
      statusChance: 100,
      target: "randomEnemy",
      duration: 5,
      tickInfo: "{target} cierpi na zatrucie i otrzymuje {damage} obrażeń.",
    }]),
  },

  {
    name: "Podpalenie",
    category: "offensive", spellPool: "chaotic",
    rarity: "uncommon", element: "fire",
    bookDescription: "Podpala wybranego przeciwnika na kilka tur.",
    damage: 0, basicCost: 0,
    reqElementalMagic: 5,
    spellTarget: "randomEnemy",
    special: "Płomień ogarnia {target}!",
    endInfo: "Ogień na {target} gaśnie.",
    statusEffects: fx([{
      type: "dot",
      element: "fire",
      damage: 3,
      statusChance: 100,
      target: "randomEnemy",
      duration: 5,
      tickInfo: "{target} płonie i otrzymuje {damage} obrażeń.",
    }]),
  },

  // Seria ładunków energii — 2 cele, 4 tury
  {
    name: "Pomniejszy ładunek energii",
    category: "offensive", spellPool: "chaotic",
    rarity: "common", element: "energy",
    bookDescription: "Ładunek energii skacze między dwoma losowymi przeciwnikami.",
    damage: 0, basicCost: 0,
    reqAstralMagic: 15,
    spellTarget: "allEnemies",
    special: "Ładunek energii zaczyna skakać między przeciwnikami!",
    endInfo: "Ładunek energii zanika.",
    statusEffects: fx([{
      type: "dot",
      element: "energy",
      damage: 2,
      statusChance: 100,
      target: "nEnemies",
      count: 2,
      duration: 4,
      tickInfo: "{target} otrzymuje {damage} obrażeń od ładunku energii.",
    }]),
  },
  {
    name: "Ładunek energii",
    category: "offensive", spellPool: "controlled",
    rarity: "common", element: "energy",
    bookDescription: "Silniejszy ładunek energii skaczący między przeciwnikami.",
    damage: 0, basicCost: 0,
    reqAstralMagic: 30,
    spellTarget: "allEnemies",
    special: "Silny ładunek energii skacze między przeciwnikami!",
    endInfo: "Ładunek energii zanika.",
    statusEffects: fx([{
      type: "dot",
      element: "energy",
      damage: 4,
      statusChance: 100,
      target: "nEnemies",
      count: 2,
      duration: 4,
      tickInfo: "{target} otrzymuje {damage} obrażeń od ładunku energii.",
    }]),
  },
  {
    name: "Potężny ładunek energii",
    category: "offensive", spellPool: "incantation",
    rarity: "common", element: "energy",
    bookDescription: "Niszczący ładunek energii skaczący między przeciwnikami.",
    damage: 0, basicCost: 0,
    reqAstralMagic: 45,
    spellTarget: "allEnemies",
    special: "Niszczący ładunek energii skacze między przeciwnikami!",
    endInfo: "Ładunek energii zanika.",
    statusEffects: fx([{
      type: "dot",
      element: "energy",
      damage: 7,
      statusChance: 100,
      target: "nEnemies",
      count: 2,
      duration: 4,
      tickInfo: "{target} otrzymuje {damage} obrażeń od ładunku energii.",
    }]),
  },

  // Seria lodowych kolców
  {
    name: "Pomniejsze lodowe kolce",
    category: "offensive", spellPool: "chaotic",
    rarity: "common", element: "water",
    bookDescription: "Lodowe kolce ranią dwóch losowych przeciwników przez kilka tur.",
    damage: 0, basicCost: 0,
    reqElementalMagic: 15,
    spellTarget: "allEnemies",
    special: "Lodowe kolce wyrastają spod nóg przeciwników!",
    endInfo: "Lodowe kolce roztapiają się.",
    statusEffects: fx([{
      type: "dot",
      element: "water",
      damage: 2,
      statusChance: 100,
      target: "nEnemies",
      count: 2,
      duration: 4,
      tickInfo: "{target} otrzymuje {damage} obrażeń od lodowych kolców.",
    }]),
  },
  {
    name: "Lodowe kolce",
    category: "offensive", spellPool: "controlled",
    rarity: "common", element: "water",
    bookDescription: "Silniejsze lodowe kolce.",
    damage: 0, basicCost: 0,
    reqElementalMagic: 30,
    spellTarget: "allEnemies",
    special: "Silne lodowe kolce wyrastają spod nóg przeciwników!",
    endInfo: "Lodowe kolce roztapiają się.",
    statusEffects: fx([{
      type: "dot",
      element: "water",
      damage: 4,
      statusChance: 100,
      target: "nEnemies",
      count: 2,
      duration: 4,
      tickInfo: "{target} otrzymuje {damage} obrażeń od lodowych kolców.",
    }]),
  },
  {
    name: "Potężne lodowe kolce",
    category: "offensive", spellPool: "incantation",
    rarity: "common", element: "water",
    bookDescription: "Niszczące lodowe kolce.",
    damage: 0, basicCost: 0,
    reqElementalMagic: 45,
    spellTarget: "allEnemies",
    special: "Ogromne lodowe kolce wyrastają spod nóg wszystkich!",
    endInfo: "Lodowe kolce roztapiają się.",
    statusEffects: fx([{
      type: "dot",
      element: "water",
      damage: 7,
      statusChance: 100,
      target: "nEnemies",
      count: 2,
      duration: 4,
      tickInfo: "{target} otrzymuje {damage} obrażeń od lodowych kolców.",
    }]),
  },

  // Seria ognistych kręgów
  {
    name: "Pomniejszy ognisty krąg",
    category: "offensive", spellPool: "chaotic",
    rarity: "common", element: "fire",
    bookDescription: "Ognisty krąg otacza dwóch losowych przeciwników.",
    damage: 0, basicCost: 0,
    reqElementalMagic: 15,
    spellTarget: "allEnemies",
    special: "Ognisty krąg otacza losowych przeciwników!",
    endInfo: "Ognisty krąg zanika.",
    statusEffects: fx([{
      type: "dot",
      element: "fire",
      damage: 2,
      statusChance: 100,
      target: "nEnemies",
      count: 2,
      duration: 4,
      tickInfo: "{target} pali się w ognistym kręgu i otrzymuje {damage} obrażeń.",
    }]),
  },
  {
    name: "Ognisty krąg",
    category: "offensive", spellPool: "controlled",
    rarity: "common", element: "fire",
    bookDescription: "Silniejszy ognisty krąg.",
    damage: 0, basicCost: 0,
    reqElementalMagic: 30,
    spellTarget: "allEnemies",
    special: "Silny ognisty krąg otacza losowych przeciwników!",
    endInfo: "Ognisty krąg zanika.",
    statusEffects: fx([{
      type: "dot",
      element: "fire",
      damage: 4,
      statusChance: 100,
      target: "nEnemies",
      count: 2,
      duration: 4,
      tickInfo: "{target} pali się w ognistym kręgu i otrzymuje {damage} obrażeń.",
    }]),
  },
  {
    name: "Potężny ognisty krąg",
    category: "offensive", spellPool: "incantation",
    rarity: "common", element: "fire",
    bookDescription: "Niszczący ognisty krąg.",
    damage: 0, basicCost: 0,
    reqElementalMagic: 45,
    spellTarget: "allEnemies",
    special: "Niszczący ognisty krąg otacza wszystkich przeciwników!",
    endInfo: "Ognisty krąg zanika.",
    statusEffects: fx([{
      type: "dot",
      element: "fire",
      damage: 7,
      statusChance: 100,
      target: "nEnemies",
      count: 2,
      duration: 4,
      tickInfo: "{target} pali się w ognistym kręgu i otrzymuje {damage} obrażeń.",
    }]),
  },

  // Seria wirów powietrza
  {
    name: "Pomniejszy wir powietrza",
    category: "offensive", spellPool: "chaotic",
    rarity: "common", element: "air",
    bookDescription: "Powietrzny wir rani dwóch losowych przeciwników.",
    damage: 0, basicCost: 0,
    reqElementalMagic: 15,
    spellTarget: "allEnemies",
    special: "Powietrzny wir zaczyna krążyć wokół przeciwników!",
    endInfo: "Wir powietrza zanika.",
    statusEffects: fx([{
      type: "dot",
      element: "air",
      damage: 2,
      statusChance: 100,
      target: "nEnemies",
      count: 2,
      duration: 4,
      tickInfo: "{target} otrzymuje {damage} obrażeń od wiru powietrza.",
    }]),
  },
  {
    name: "Wir powietrza",
    category: "offensive", spellPool: "controlled",
    rarity: "common", element: "air",
    bookDescription: "Silniejszy powietrzny wir.",
    damage: 0, basicCost: 0,
    reqElementalMagic: 30,
    spellTarget: "allEnemies",
    special: "Silny powietrzny wir krąży wokół przeciwników!",
    endInfo: "Wir powietrza zanika.",
    statusEffects: fx([{
      type: "dot",
      element: "air",
      damage: 4,
      statusChance: 100,
      target: "nEnemies",
      count: 2,
      duration: 4,
      tickInfo: "{target} otrzymuje {damage} obrażeń od wiru powietrza.",
    }]),
  },
  {
    name: "Potężny wir powietrza",
    category: "offensive", spellPool: "incantation",
    rarity: "common", element: "air",
    bookDescription: "Niszczący powietrzny wir.",
    damage: 0, basicCost: 0,
    reqElementalMagic: 45,
    spellTarget: "allEnemies",
    special: "Niszczący powietrzny wir szaleje wokół wszystkich!",
    endInfo: "Wir powietrza zanika.",
    statusEffects: fx([{
      type: "dot",
      element: "air",
      damage: 7,
      statusChance: 100,
      target: "nEnemies",
      count: 2,
      duration: 4,
      tickInfo: "{target} otrzymuje {damage} obrażeń od wiru powietrza.",
    }]),
  },

  // Seria wstrząsów ziemi
  {
    name: "Pomniejsze wstrząsy",
    category: "offensive", spellPool: "chaotic",
    rarity: "common", element: "earth",
    bookDescription: "Wstrząsy ziemi ranią dwóch losowych przeciwników.",
    damage: 0, basicCost: 0,
    reqElementalMagic: 15,
    spellTarget: "allEnemies",
    special: "Ziemia trzęsie się pod nogami przeciwników!",
    endInfo: "Wstrząsy ustają.",
    statusEffects: fx([{
      type: "dot",
      element: "earth",
      damage: 2,
      statusChance: 100,
      target: "nEnemies",
      count: 2,
      duration: 4,
      tickInfo: "{target} otrzymuje {damage} obrażeń od wstrząsów.",
    }]),
  },
  {
    name: "Wstrząsy",
    category: "offensive", spellPool: "controlled",
    rarity: "common", element: "earth",
    bookDescription: "Silniejsze wstrząsy ziemi.",
    damage: 0, basicCost: 0,
    reqElementalMagic: 30,
    spellTarget: "allEnemies",
    special: "Silne wstrząsy ziemi uderzają w przeciwników!",
    endInfo: "Wstrząsy ustają.",
    statusEffects: fx([{
      type: "dot",
      element: "earth",
      damage: 4,
      statusChance: 100,
      target: "nEnemies",
      count: 2,
      duration: 4,
      tickInfo: "{target} otrzymuje {damage} obrażeń od wstrząsów.",
    }]),
  },
  {
    name: "Potężne wstrząsy",
    category: "offensive", spellPool: "incantation",
    rarity: "common", element: "earth",
    bookDescription: "Niszczące wstrząsy ziemi.",
    damage: 0, basicCost: 0,
    reqElementalMagic: 45,
    spellTarget: "allEnemies",
    special: "Potężne wstrząsy rozrywają ziemię pod wszystkimi!",
    endInfo: "Wstrząsy ustają.",
    statusEffects: fx([{
      type: "dot",
      element: "earth",
      damage: 7,
      statusChance: 100,
      target: "nEnemies",
      count: 2,
      duration: 4,
      tickInfo: "{target} otrzymuje {damage} obrażeń od wstrząsów.",
    }]),
  },

  // Seria mrocznych wirów
  {
    name: "Pomniejszy mroczny wir",
    category: "offensive", spellPool: "chaotic",
    rarity: "common", element: "chaos",
    bookDescription: "Mroczny wir krąży wokół trzech losowych przeciwników.",
    damage: 0, basicCost: 0,
    reqBloodMagic: 5,
    spellTarget: "allEnemies",
    special: "Mroczny wir ogarnia przeciwników!",
    endInfo: "Mroczny wir zanika.",
    statusEffects: fx([{
      type: "dot",
      element: "chaos",
      damage: 1,
      statusChance: 100,
      target: "nEnemies",
      count: 3,
      duration: 3,
      tickInfo: "{target} otrzymuje {damage} obrażeń od mrocznego wiru.",
    }]),
  },
  {
    name: "Mroczny wir",
    category: "offensive", spellPool: "controlled",
    rarity: "common", element: "chaos",
    bookDescription: "Silniejszy mroczny wir.",
    damage: 0, basicCost: 0,
    reqBloodMagic: 20,
    spellTarget: "allEnemies",
    special: "Silny mroczny wir ogarnia przeciwników!",
    endInfo: "Mroczny wir zanika.",
    statusEffects: fx([{
      type: "dot",
      element: "chaos",
      damage: 3,
      statusChance: 100,
      target: "nEnemies",
      count: 3,
      duration: 3,
      tickInfo: "{target} otrzymuje {damage} obrażeń od mrocznego wiru.",
    }]),
  },
  {
    name: "Potężny mroczny wir",
    category: "offensive", spellPool: "incantation",
    rarity: "common", element: "chaos",
    bookDescription: "Niszczący mroczny wir.",
    damage: 0, basicCost: 0,
    reqBloodMagic: 35,
    spellTarget: "allEnemies",
    special: "Niszczący mroczny wir ogarnia wszystkich!",
    endInfo: "Mroczny wir zanika.",
    statusEffects: fx([{
      type: "dot",
      element: "chaos",
      damage: 5,
      statusChance: 100,
      target: "nEnemies",
      count: 3,
      duration: 3,
      tickInfo: "{target} otrzymuje {damage} obrażeń od mrocznego wiru.",
    }]),
  },

  // ════════════════════════════════════════════════════════════════════════════
  // DAMAGE_ON_MOVE — obrażenia przy każdej akcji
  // ════════════════════════════════════════════════════════════════════════════

  {
    name: "Lawa",
    category: "offensive", spellPool: "chaotic",
    rarity: "uncommon", element: "fire",
    bookDescription: "Pokrywa pole walki lawą — każdy ruch przeciwnika grozi oparzeniem.",
    damage: 0, basicCost: 0,
    reqElementalMagic: 10,
    spellTarget: "allEnemies",
    special: "Na pobojowisku pojawia się mnóstwo lawy!",
    endInfo: "Lawa zastyga i znika.",
    statusEffects: fx([{
      type: "damage_on_move",
      element: "fire",
      damage: 2,
      statusChance: 50,
      target: "allEnemies",
      duration: 3,
      tickInfo: "{target} ochlapała lawa, zadając {damage} obrażeń.",
      failTickInfo: "{target} ostrożnie omija lawę.",
    }]),
  },

  {
    name: "Morowe powietrze",
    category: "offensive", spellPool: "chaotic",
    rarity: "uncommon", element: "death",
    bookDescription: "Śmiercionośne powietrze — każdy ruch przeciwnika grozi zatruciem.",
    damage: 0, basicCost: 0,
    reqBloodMagic: 10,
    spellTarget: "allEnemies",
    special: "Pobojowisko wypełnia śmiercionośne powietrze.",
    endInfo: "Morowe powietrze zanika.",
    statusEffects: fx([{
      type: "damage_on_move",
      element: "death",
      damage: 2,
      statusChance: 50,
      target: "allEnemies",
      duration: 3,
      tickInfo: "Morowe powietrze wypełnia płuca {target} zadając {damage} obrażeń.",
      failTickInfo: "{target} wstrzymuje oddech.",
    }]),
  },

  {
    name: "Zdradliwe bagno",
    category: "offensive", spellPool: "chaotic",
    rarity: "uncommon", element: "earth",
    bookDescription: "Ruchome bagno — każdy krok może wciągnąć przeciwnika głębiej.",
    damage: 0, basicCost: 0,
    reqElementalMagic: 10,
    spellTarget: "allEnemies",
    special: "Pobojowisko zalewa nieprzeniknione, ruchome bagno.",
    endInfo: "Bagno zanika.",
    statusEffects: fx([{
      type: "damage_on_move",
      element: "earth",
      damage: 2,
      statusChance: 50,
      target: "allEnemies",
      duration: 3,
      tickInfo: "Bagno wciąga {target} zadając {damage} obrażeń.",
      failTickInfo: "{target} wyswobadza nogę z bagna.",
    }]),
  },

  {
    name: "Lodowisko",
    category: "offensive", spellPool: "chaotic",
    rarity: "uncommon", element: "water",
    bookDescription: "Zamarza podłoże — każdy krok przeciwnika grozi upadkiem.",
    damage: 0, basicCost: 0,
    reqElementalMagic: 10,
    spellTarget: "allEnemies",
    special: "Całe podłoże zostaje skute lodem — strasznie ślisko!",
    endInfo: "Lód się roztapia.",
    statusEffects: fx([{
      type: "damage_on_move",
      element: "water",
      damage: 2,
      statusChance: 50,
      target: "allEnemies",
      duration: 3,
      tickInfo: "{target} poślizgnął się na lodzie i otrzymał {damage} obrażeń.",
      failTickInfo: "{target} zachowuje równowagę.",
    }]),
  },

  {
    name: "Rozstrzaskane lustra",
    category: "offensive", spellPool: "chaotic",
    rarity: "uncommon", element: "none",
    bookDescription: "Rozbite szkło na polu walki grozi każdemu, kto się poruszy.",
    damage: 0, basicCost: 0,
    spellTarget: "all",
    special: "Dziesiątki luster roztrzaskują się o podłoże pokrywając je szkłem.",
    endInfo: "Kawałki szkła magicznie znikają.",
    statusEffects: fx([{
      type: "damage_on_move",
      element: "none",
      damage: 2,
      statusChance: 50,
      target: "all",
      duration: 3,
      tickInfo: "Walające się szkło rani {target} zadając {damage} obrażeń.",
      failTickInfo: "{target} omija szkło.",
    }]),
  },

  // ════════════════════════════════════════════════════════════════════════════
  // STUN — ogłuszenie
  // ════════════════════════════════════════════════════════════════════════════

  {
    name: "Prześcieradło",
    category: "offensive", spellPool: "chaotic",
    rarity: "common", element: "none",
    bookDescription: "Prześcieradło blokuje ruchy losowego wroga.",
    damage: 0, basicCost: 0,
    spellTarget: "randomEnemy",
    special: "Prześcieradło materializuje się nad {target} i blokuje jego ruchy!",
    endInfo: "{target} wyplątuje się z prześcieradła.",
    statusEffects: fx([{
      type: "stun",
      statusChance: 100,
      target: "randomEnemy",
      duration: 1,
      tickInfo: "{target} jest owinięty w prześcieradło — traci akcję!",
      failTickInfo: "",
    }]),
  },

  {
    name: "Podmuch",
    category: "offensive", spellPool: "chaotic",
    rarity: "common", element: "air",
    bookDescription: "Silny podmuch może wytrącić przeciwnika z równowagi.",
    damage: 1, basicCost: 0,
    reqElementalMagic: 5,
    spellTarget: "randomEnemy",
    special: "Mocny podmuch uderza w {target} zadając {damage} obrażeń.",
    endInfo: "{target} odzyskuje równowagę.",
    statusEffects: fx([{
      type: "stun",
      statusChance: 25,
      target: "randomEnemy",
      duration: 1,
      tickInfo: "Podmuch wytrąca {target} z równowagi — traci akcję!",
      failTickInfo: "{target} utrzymuje równowagę.",
    }]),
  },

  {
    name: "Oślepienie",
    category: "offensive", spellPool: "chaotic",
    rarity: "uncommon", element: "none",
    bookDescription: "Potężny błysk oślepia losowego przeciwnika na kilka tur.",
    damage: 0, basicCost: 0,
    reqAstralMagic: 5,
    spellTarget: "randomEnemy",
    special: "Potężny błysk oślepia {target}!",
    endInfo: "{target} odzyskuje wzrok.",
    statusEffects: fx([{
      type: "stun",
      statusChance: 100,
      target: "randomEnemy",
      duration: 3,
      tickInfo: "{target} jest oślepiony — traci akcję!",
      failTickInfo: "",
    }]),
  },

  {
    name: "Motyle",
    category: "offensive", spellPool: "chaotic",
    rarity: "uncommon", element: "none",
    bookDescription: "Chmara motyli zauroczenia zatrzymuje wszystkich na jedną turę.",
    damage: 0, basicCost: 0,
    reqBloodMagic: 5,
    spellTarget: "all",
    special: "Chmara pięknych, kolorowych motyli pojawia się — wszyscy stoją zauroczeni!",
    statusEffects: fx([{
      type: "stun",
      statusChance: 100,
      target: "all",
      duration: 1,
      tickInfo: "{target} stoi zauroczony motylami — traci akcję!",
      failTickInfo: "",
    }]),
  },

  // ════════════════════════════════════════════════════════════════════════════
  // VULNERABLE — podatność na żywioł
  // ════════════════════════════════════════════════════════════════════════════

  {
    name: "Wodna kula",
    category: "offensive", spellPool: "chaotic",
    rarity: "uncommon", element: "water",
    bookDescription: "Wodna kula moczy cel, czyniąc go podatnym na obrażenia od energii.",
    damage: 5, basicCost: 0,
    reqElementalMagic: 10,
    spellTarget: "randomEnemy",
    special: "Duża wodna kula uderza w {target} zadając {damage} obrażeń i mocząc go.",
    endInfo: "{target} wysycha.",
    statusEffects: fx([{
      type: "vulnerable",
      element: "energy",
      value: 25,
      target: "randomEnemy",
      duration: 4,
    }]),
  },

  {
    name: "Strumień wody",
    category: "offensive", spellPool: "chaotic",
    rarity: "uncommon", element: "water",
    bookDescription: "Strumień wody pod ciśnieniem — cel staje się bardziej podatny na energię.",
    damage: 1, basicCost: 0,
    reqElementalMagic: 10,
    spellTarget: "randomEnemy",
    special: "Strumień wody pod ciśnieniem uderza w {target} zadając {damage} obrażeń.",
    endInfo: "{target} wysycha.",
    statusEffects: fx([{
      type: "vulnerable",
      element: "energy",
      value: 50,
      target: "randomEnemy",
      duration: 5,
    }]),
  },

  {
    name: "Piorun kulisty",
    category: "offensive", spellPool: "chaotic",
    rarity: "uncommon", element: "energy",
    bookDescription: "Piorun naelektryzowuje cel, czyniąc go podatnym na obrażenia od wody.",
    damage: 5, basicCost: 0,
    reqAstralMagic: 10,
    spellTarget: "randomEnemy",
    special: "Mały piorun kulisty uderza w {target} zadając {damage} obrażeń i naelektryzowuje go.",
    endInfo: "{target} nie jest już naelektryzowany.",
    statusEffects: fx([{
      type: "vulnerable",
      element: "water",
      value: 25,
      target: "randomEnemy",
      duration: 5,
    }]),
  },

] as const;