export const ALIGNMENT_PATHS = {
  GOOD: {
    LAWFUL: "STRAŻNICY ŚWITU",
    NEUTRAL: "WĘDROWCY ŹRÓDEŁ",
    CHAOTIC: "BURZOWI PIELGRZYMI",
  },

  NEUTRAL: {
    LAWFUL: "RUNICZNI SĘDZIOWIE",
    NEUTRAL: "TKACZE MGŁY",
    CHAOTIC: "ROZDARCI",
  },

  EVIL: {
    LAWFUL: "ŻELAZNE WIDMA",
    NEUTRAL: "POŻERACZE SZEPTÓW",
    CHAOTIC: "DZIECI OTCHŁANI",
  },
} as const;

export const PATH_LOCKS: Record<string, string[]> = {
  "STRAŻNICY ŚWITU": [
    "SYNOWIE PUSTKI",
    "POŻERACZE ECH",
    "GADERY",
  ],

  "WĘDROWCY ŹRÓDEŁ": [
    "SYNOWIE PUSTKI",
    "EGZEKUTORZY WOLI",
  ],

  "BURZOWI PIELGRZYMI": [
    "EGZEKUTORZY WOLI",
    "POŻERACZE ECH",
    "ARBITRZY RUN",
  ],

  "RUNICZNI SĘDZIOWIE": [
    "SYNOWIE PUSTKI",
    "BURZOWI WĘDROWCY",
  ],

  "TKACZE MGŁY": [
    "LUMINARZY",
    "SYNOWIE PUSTKI",
  ],

  "ROZDARCI": [
    "LUMINARZY",
    "ARBITRZY RUN",
  ],

  "ŻELAZNE WIDMA": [
    "BURZOWI WĘDROWCY",
    "SZEPTACZE ŹRÓDEŁ",
    "TKACZE ETERU",
  ],

  "POŻERACZE SZEPTÓW": [
    "BURZOWI WĘDROWCY",
    "LUMINARZY",
  ],

  "DZIECI OTCHŁANI": [
    "LUMINARZY",
    "SZEPTACZE ŹRÓDEŁ",
    "ARBITRZY RUN",
  ],
};